import { CasoContent } from './caso-content';
import { CasosContent } from './casos-content';
import { ClienteContent } from './cliente-content';
import { ClientesContent } from './clientes-content';
import { CuotaContent } from './cuota-content';
import { ExpedienteContent } from './expediente-content';
import { FaqContent } from './faq-content';
import { GeneralContent } from './general-content';
import { GoodbyeContent } from './goodbye-content';
import { HomeContent } from './home-content';
import { LoginContent } from './login-content';
import { MovimientoContent } from './movimiento-content';
import { NotAllowContent } from './not-allow-content';
import { NotFoundContent } from './not-found-content';
import { OrganizationContent } from './organization-content';
import { PagoContent } from './pago-content';
import { PagosContent } from './pagos-content';
import { RecursosContent } from './recursos-content';
import { RegisterContent } from './register-content';
import { SelectClienteContent } from './select-cliente-content';
import { SelectDependenciasContent } from './select-dependencia-content';
import { SelectEntitiesContent } from './select-entities-content';
import { SettingsContent } from './settings-content';
import { TareaContent } from './tarea-content';
import { ThanksContent } from './thanks-content';
import { TurnoContent } from './turno-content';
import { UploadFilesContent } from './uploadFiles-content';
import { UserContent } from './user-content';

export interface AppContent {
    faq: FaqContent;
    caso: CasoContent;
    casos: CasosContent;
    cliente: ClienteContent;
    clientes: ClientesContent;
    cuota: CuotaContent;
    expediente: ExpedienteContent;
    home: HomeContent;
    login: LoginContent;
    movimiento: MovimientoContent;
    pago: PagoContent;
    pagos: PagosContent;
    settings: SettingsContent;
    turno: TurnoContent;
    recursos: RecursosContent;
    uploadFiles: UploadFilesContent;
    selectEntitiesModal: SelectEntitiesContent;
    tarea: TareaContent;
    selectDependencia: SelectDependenciasContent;
    selectCliente: SelectClienteContent;
    organization: OrganizationContent;
    user: UserContent;
    register: RegisterContent;
    notFound: NotFoundContent;
    notAllow: NotAllowContent;
    thanks: ThanksContent;
    general: GeneralContent;
    goodbye: GoodbyeContent;
}
